baseURL = 'https://UNIQsandbox.com'
languageCode = 'en-us'
title = 'UNIQsandbox | Architecture of Logic'
theme = 'PaperMod'

[params]
    env = 'production'
    author = 'doitandy'
    description = 'Where Legacy Meets Logic'

    [params.profileMode]
        enabled = true
        title = 'UNIQsandbox'
        subtitle = 'IT Architect | 1,100+ Books | Books & Barbells'

[[menu.main]]
    name = 'Thought'
    url = '/thought'
    weight = 10
[[menu.main]]
    name = 'GTM'
    url = '/gtm'
    weight = 20
[[menu.main]]
    name = 'Lab'
    url = '/lab'
    weight = 30
